name: apptruyen
description: "App đọc truyện Flutter + AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/database/truyen.db
    - assets/avatars/
    - assets/images/
    - assets/database/images/bach_hop/
    - assets/database/images/co_dai/
    - assets/database/images/cung_dau/
    - assets/database/images/dam_my/
    - assets/database/images/di_gioi/
    - assets/database/images/di_nang/
    - assets/database/images/do_thi/
    - assets/database/images/he_thong/
    - assets/database/images/hien_dai/
    - assets/database/images/huyen_huyen/
    - assets/database/images/khac/
    - assets/database/images/khoa_huyen/
    - assets/database/images/kiem_hiep/
    - assets/database/images/lich_su/
    - assets/database/images/linh_di/
    - assets/database/images/ngon_tinh/
    - assets/database/images/nu_cuong/
    - assets/database/images/quan_su/
    - assets/database/images/quan_truong/
    - assets/database/images/tien_hiep/
    - assets/database/images/tieu_thuyet/
    - assets/database/images/trinh_tham/
    - assets/database/images/trong_sinh/
    - assets/database/images/truyen_teen/
    - assets/database/images/vong_du/
    - assets/database/images/xuyen_khong/
    - assets/database/images/xuyen_nhanh/
    
#pub get cho icon app (flutter pub run flutter_launcher_icons)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"